server {
    listen 80;
    absolute_redirect off;

    location /metrics {
        proxy_pass http://backend/metrics;
    }

    location /movies {
        root /usr/share/nginx/html/;
        index movies.html;
        try_files $uri /movies.html;
    }

    location /backend {
        proxy_pass http://backend;
    }

    location / {
        return 302 movies;
    }

}
