name: Docker Build and Test

on:
  push:
    branches: [ "lab1", "lab2" ]
  pull_request:
    branches: [ "lab1", "lab2" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
