name: Docker Build and Test

on:
  push:
    branches: [ "lab1", "lab2" ]
  pull_request:
    branches: [ "lab1", "lab2" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up --build -d


      - name: Wait for services to be ready
        run: |
          docker-compose exec backend curl -f http://localhost || exit 1
          docker-compose exec nginx curl -f http://localhost || exit 1

      - name: Tear down the services
        run: docker-compose down